// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmMMcfG87w_KlyW2yTZy190TwFOeyEipw',
    appId: '1:124846076490:web:830affccbe030cd0402cb3',
    messagingSenderId: '124846076490',
    projectId: 'service-squad-517cf',
    authDomain: 'service-squad-517cf.firebaseapp.com',
    storageBucket: 'service-squad-517cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnRO4SruNuAVEFY-XBlGlY-UcnolU0JsI',
    appId: '1:124846076490:android:74d13200c75625ba402cb3',
    messagingSenderId: '124846076490',
    projectId: 'service-squad-517cf',
    storageBucket: 'service-squad-517cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHMZP4zF4STlaKnbjToslHccseOEzyco',
    appId: '1:124846076490:ios:fbf8588783fb3db9402cb3',
    messagingSenderId: '124846076490',
    projectId: 'service-squad-517cf',
    storageBucket: 'service-squad-517cf.appspot.com',
    iosBundleId: 'com.example.serviceSquad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdHMZP4zF4STlaKnbjToslHccseOEzyco',
    appId: '1:124846076490:ios:03f866c5850f2e4b402cb3',
    messagingSenderId: '124846076490',
    projectId: 'service-squad-517cf',
    storageBucket: 'service-squad-517cf.appspot.com',
    iosBundleId: 'com.example.serviceSquad.RunnerTests',
  );
}
